Repository cdapio/hydrator-plugins, pull requests merged in 2020-06, with the labels that each got.

#1114 Feature release/cdap 62 agg cherry pick
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/AggregateResult.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/DedupAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/DedupConfig.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/DistinctAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/GroupByAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/RecordReducibleAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AggregateFunction.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Avg.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectList.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectSet.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Count.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountAll.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountDistinct.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/First.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Last.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Max.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MaxSelection.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Min.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MinSelection.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/NumberFunction.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/NumberSelection.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/RecordFunctionLifecycle.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/SelectionFunction.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Stddev.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Sum.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Variance.java
  core-plugins/src/test/java/io/cdap/plugin/batch/ETLBatchTestBase.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/DedupConfigTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/DedupTestRun.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/DistinctTestRun.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/GroupByTestRun.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AggregateFunctionTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AvgTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectListTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectSetTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountAllTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountDistinctTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/FirstTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LastTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MaxTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MinTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/NumberTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/StdTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/SumTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/VarianceTest.java
Labels: 2.4

#1101 Update Hasher-transform.json
  transform-plugins/widgets/Hasher-transform.json
Labels: 2.4-cherry-pick

#1104 PLUGIN-99 fix parquet format to handle group type correctly
  format-parquet/src/main/java/org/apache/parquet/avro/AvroIndexedRecordConverter.java
Labels: 2.4-cherry-pick

#1126 (PLUGIN-165) Added fetchSize property to DBSource
  database-plugins/src/main/java/io/cdap/plugin/DBUtils.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/ForwardingConnection.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/NoOpCommitConnection.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/ConnectionWithFetchSize.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/DBSource.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/DataDrivenETLDBInputFormat.java
  database-plugins/src/test/java/io/cdap/plugin/db/batch/source/DBSourceTestRun.java
  database-plugins/widgets/Database-batchsource.json
Labels: 2.3

#1127 (PLUGIN-165) Added fetchSize property to DBSource
  database-plugins/src/main/java/io/cdap/plugin/DBUtils.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/ForwardingConnection.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/NoOpCommitConnection.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/ConnectionWithFetchSize.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/DBSource.java
  database-plugins/src/main/java/io/cdap/plugin/db/batch/source/DataDrivenETLDBInputFormat.java
  database-plugins/src/test/java/io/cdap/plugin/db/batch/source/DBSourceTestRun.java
  database-plugins/widgets/Database-batchsource.json
Labels: 2.4
