Repository cdapio/hydrator-plugins, pull requests merged in 2021-03, with the labels that each got.

#1352 [PLUGIN-646] Fix joiner widget for conditionType
  core-plugins/widgets/Joiner-batchjoiner.json
Labels: 2.6, bug, cherry-pick

#1351 [PLUGIN-646] Fix joiner widget for conditionType
  core-plugins/widgets/Joiner-batchjoiner.json
Labels: bug

#1299 Implement CSV Schema Detection Plugin
  core-plugins/docs/File-batchsource.md
  core-plugins/src/main/java/io/cdap/plugin/batch/source/FileSourceConfig.java
  core-plugins/widgets/File-batchsource.json
  format-avro/src/main/java/io/cdap/plugin/format/avro/input/AvroInputFormatProvider.java
  format-common/src/main/java/io/cdap/plugin/format/input/PathTrackingConfig.java
  format-delimited/pom.xml
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/common/DataType.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/common/DataTypeDetectorStatusKeeper.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/common/DataTypeDetectorUtils.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/common/DateTimePattern.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/common/TypeInference.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/dto/DateTimeStandard.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/dto/SupportedDateTimeStandards.java
  format-delimited/src/main/java/io/cdap/plugin/format/delimited/input/DelimitedConfig.java
  format-delimited/src/main/resources/datetime-regex.json
  format-delimited/src/main/resources/time-regex.json
  format-delimited/src/test/java/io/cdap/plugin/format/delimited/common/DataTypeDetectorUtilsTest.java
  format-delimited/src/test/java/io/cdap/plugin/format/delimited/dq/TypeInferenceTest.java
  format-parquet/src/main/java/io/cdap/plugin/format/parquet/input/ParquetInputFormatProvider.java
Labels: 2.6
