Repository cdapio/hydrator-plugins, pull requests merged in 2021-05, with the labels that each got.

#1370 PLUGIN-637: Date and time types don't work with delimited formats in File source.
  core-plugins/pom.xml
  core-plugins/src/main/java/io/cdap/plugin/batch/source/FileSourceConfig.java
  core-plugins/src/test/java/io/cdap/plugin/batch/source/FileBatchSourceTest.java
Labels: build

#1350 PLUGIN-595/GroupByAggregator append functions with conditional functions
  core-plugins/docs/GroupByAggregate-batchaggregator.md
  core-plugins/pom.xml
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/GroupByAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/GroupByConfig.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AggregateFunction.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AnyIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AvgIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectListIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectSetIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ConcatDistinctIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ConcatIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Condition.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CorrectedSumOfSquaresIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountDistinctIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/JexlCondition.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LogicalAndIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LogicalOrIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LongestStringIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MaxIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MinIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ShortestStringIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/StddevIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/SumIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/SumOfSquaresIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/VarianceIf.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/GroupByTestRun.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AnyIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AvgIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AvgTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectListIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectSetIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ConcatDistinctIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ConcatIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CorrectedSumOfSquaresIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountDistinctIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LogicalAndIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LogicalOrIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LongestStringIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MaxIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MinIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ShortestStringIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/StdIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/SumIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/SumOfSquaresIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/VarianceIfTest.java
  core-plugins/widgets/GroupByAggregate-batchaggregator.json
Labels: build

#1384 GroupByAggregator append functions with conditional functions - CherryPick for release/2.6
  core-plugins/docs/GroupByAggregate-batchaggregator.md
  core-plugins/pom.xml
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/GroupByAggregator.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/GroupByConfig.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AggregateFunction.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AnyIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/AvgIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectListIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CollectSetIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ConcatDistinctIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ConcatIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/Condition.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CorrectedSumOfSquaresIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountDistinctIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/CountIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/JexlCondition.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LogicalAndIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LogicalOrIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/LongestStringIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MaxIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/MinIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/ShortestStringIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/StddevIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/SumIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/SumOfSquaresIf.java
  core-plugins/src/main/java/io/cdap/plugin/batch/aggregator/function/VarianceIf.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/GroupByTestRun.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AnyIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AvgIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/AvgTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectListIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CollectSetIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ConcatDistinctIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ConcatIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CorrectedSumOfSquaresIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountDistinctIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/CountIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LogicalAndIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LogicalOrIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/LongestStringIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MaxIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/MinIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/ShortestStringIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/StdIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/SumIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/SumOfSquaresIfTest.java
  core-plugins/src/test/java/io/cdap/plugin/batch/aggregator/function/VarianceIfTest.java
  core-plugins/widgets/GroupByAggregate-batchaggregator.json
Labels: build

#1387 PLUGIN 259: Cassandra plugin from Hub do not work.
  cassandra-plugins/pom.xml
Labels: build

#1365 [PLUGIN-669] Fix Joiner dynamic widget filter to show basic options w…
  core-plugins/widgets/Joiner-batchjoiner.json
Labels: bug

#1366 [PLUGIN-669] Fix Joiner dynamic widget filter to show basic options w…
  core-plugins/widgets/Joiner-batchjoiner.json
Labels: 2.6, bug, cherry-pick

#1392 Fix a bug in bytes read metric
  database-plugins/src/main/java/io/cdap/plugin/DBRecord.java
Labels: build

#1393 Fix a bug in bytes read metric
  database-plugins/src/main/java/io/cdap/plugin/DBRecord.java
Labels: build

#1396 Exclude some dependencies from hive-exec
  pom.xml
Labels: build

#1402 [RELEASE-6.4.1] Remove SNAPSHOTs
  cassandra-plugins/pom.xml
  core-plugins/pom.xml
  database-plugins/pom.xml
  format-avro/pom.xml
  format-blob/pom.xml
  format-common/pom.xml
  format-delimited/pom.xml
  format-json/pom.xml
  format-orc/pom.xml
  format-parquet/pom.xml
  format-text/pom.xml
  hbase-plugins/pom.xml
  hive-plugins/pom.xml
  http-plugins/pom.xml
  hydrator-common/pom.xml
  mongodb-plugins/pom.xml
  pom.xml
  solrsearch-plugins/pom.xml
  spark-plugins/pom.xml
  transform-plugins/pom.xml
Labels: automated-release

#1407 [RELEASE-6.4.1] Bump to SNAPSHOT
  cassandra-plugins/pom.xml
  core-plugins/pom.xml
  database-plugins/pom.xml
  format-avro/pom.xml
  format-blob/pom.xml
  format-common/pom.xml
  format-delimited/pom.xml
  format-json/pom.xml
  format-orc/pom.xml
  format-parquet/pom.xml
  format-text/pom.xml
  hbase-plugins/pom.xml
  hive-plugins/pom.xml
  http-plugins/pom.xml
  hydrator-common/pom.xml
  mongodb-plugins/pom.xml
  pom.xml
  solrsearch-plugins/pom.xml
  spark-plugins/pom.xml
  transform-plugins/pom.xml
Labels: automated-release
